spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    content-type: text/html
  # mvc静态资源
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  # 文件上传限制
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      max-file-size: 50MB
  # 邮件模板
  freemarker:
    template-loader-path: classpath:/static/mail/
    suffix: .ftl
    enabled: true
    cache: false
    charset: UTF-8
    content-type: text/html
    allow-request-override: false
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false

## MyBatis的相关配置
mybatis:
  # 映射文件位置
  mapper-locations: classpath:mapper/*.xml
  # 别名扫描包
  type-aliases-package: com.xxx.pojo
  # 输出SQL执行语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义starter
com:
  yqqyyq:
    enabled: true
    name: yqqyyqxxx
    hobby: code